# Site settings
title: Tudor Saitoc
email: tudor@saitoc.me
description: "Tech geek, Technologist, Frontend Dev, Developer, Nerdy Boy, Technokid!"
username: tudr
baseurl: "/blog"
url: "https://blog.tudr.co"
paginate: 10
paginate_path: "/halaman/:num/"

# Build settings`
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
highlighter: rouge
